SELECT SUBSTRING(v_stt_processo.COD_INSTANCIA, 1, 1024) AS "COD_INSTANCIA (v_stt_processo)",
  v_stt_processo.DAT_ADMISSAO_TERCEIRO AS DAT_ADMISSAO_TERCEIRO,
  v_stt_processo.DAT_AJUIZAMENTO AS DAT_AJUIZAMENTO,
/*  `v_stt_processo`.`DAT_AUDIENCIA` AS `DAT_AUDIENCIA`,*/
 /* `v_stt_processo`.`HOR_AUDIENCIA` AS `HOR_AUDIENCIA`,*/
  DATE_FORMAT(`v_stt_processo`.`DAT_AUDIENCIA`,'%Y-%m-%d') AS DAT_AUDIENCIA,
 CASE WHEN TIME_FORMAT(v_stt_processo.DAT_AUDIENCIA,'%T') <>  '03:00:00' THEN TIME_FORMAT(v_stt_processo.DAT_AUDIENCIA,'%T') END AS HOR_AUDIENCIA,
  v_stt_processo.DAT_CRIACAO AS DAT_CRIACAO,
  v_stt_processo.DAT_CRIACAO_REGISTRO AS "DAT_CRIACAO_REGISTRO (v_stt_processo)",
  v_stt_processo.DAT_DEFESA AS DAT_DEFESA,
  v_stt_processo.DAT_DEMISSAO_TERCEIRO AS DAT_DEMISSAO_TERCEIRO,
  v_stt_processo.DAT_ENVIO_GESTOR AS DAT_ENVIO_GESTOR,
  v_stt_processo.DAT_FIM_MONITORIA_RECLAMANTE AS DAT_FIM_MONITORIA_RECLAMANTE,
  v_stt_processo.DAT_FIM_PERIODO_RECLAMADO AS DAT_FIM_PERIODO_RECLAMADO,
  v_stt_processo.DAT_INI_MONITORIA_RECLAMANTE AS DAT_INI_MONITORIA_RECLAMANTE,
  v_stt_processo.DAT_INI_PERIODO_RECLAMADO AS DAT_INI_PERIODO_RECLAMADO,
  v_stt_processo.DAT_PRAZO_ATENDIMENTO AS DAT_PRAZO_ATENDIMENTO,
  v_stt_processo.DAT_RECEBIMENTO_CLARO AS DAT_RECEBIMENTO_CLARO,
  v_stt_processo.DAT_RECEBIMENTO_ESCRITORIO AS DAT_RECEBIMENTO_ESCRITORIO,
  SUBSTRING(v_stt_processo.DSC_IND_CRITICIDADE, 1, 1024) AS DSC_CRITICIDADE,
  SUBSTRING(v_stt_processo.DSC_FUNCAO_REALIZADO_TERCEIRO, 1, 1024) AS DSC_FUNCAO_REAL_TERC,
  SUBSTRING(v_stt_processo.DSC_GRUPO_FAMILIA, 1, 1024) AS DSC_GRUPO_FAMILIA,
  SUBSTRING(v_stt_processo.DSC_JUSTIFICATIVA, 1, 1024) AS DSC_JUSTIFICATIVA,
  SUBSTRING(v_stt_processo.DSC_JUST_ALT_EMPRES_MONITORADO, 1, 1024) AS DSC_JUST_ALT_EMP_MONITORAD,
  SUBSTRING(v_stt_processo.DSC_JUSTIFICATIVA_CRITICIDADE, 1, 1024) AS DSC_JUST_CRITICIDADE,
  SUBSTRING(v_stt_processo.DSC_JUST_RECLAMANTE_MONITORADO, 1, 1024) AS DSC_JUST_RECLAM_MONITORADO,
  SUBSTRING(v_stt_processo.DSC_LOCAL_ARQUIVO_ANEXO, 1, 1024) AS DSC_LOCAL_ARQUIVO_ANEXO,
  SUBSTRING(v_stt_processo.DSC_NOME_ADVOGADO_INTERNO_RESP, 1, 1024) AS DSC_NOM_ADVOG_INTERNO_RESP,
  SUBSTRING(v_stt_processo.DSC_NOME_ADVOGADO_RECLAMANTE, 1, 1024) AS DSC_NOM_ADVOG_RECLAMANTE,
  SUBSTRING(v_stt_processo.DSC_NOME_AREA_ABERTURA, 1, 1024) AS DSC_NOM_AREA_ABERTURA,
  SUBSTRING(v_stt_processo.DSC_NOME_COMARCA, 1, 1024) AS DSC_NOM_COMARCA,
  SUBSTRING(v_stt_processo.DSC_NOME_EMPRESA, 1, 1024) AS DSC_NOM_EMPRESA,
  SUBSTRING(v_stt_processo.DSC_NOME_EMPRESA_ENVOLVIDA, 1, 1024) AS DSC_NOM_EMPRESA_ENVOLVIDA,
  SUBSTRING(v_stt_processo.DSC_NOME_EMPRESA_ORIGEM, 1, 1024) AS DSC_NOM_EMPRESA_ORIGEM,
  SUBSTRING(v_stt_processo.DSC_NOME_EMPRESA_TERCEIRIZADA, 1, 1024) AS DSC_NOM_EMPRESA_TERCEIRIZADA,
  SUBSTRING(replace(v_stt_processo.dsc_escritorio_abertura, "ESCRITORIO_",""), 1, 1024) AS DSC_NOM_ESCRITORIO_ABERTURA,
  SUBSTRING(v_stt_processo.DSC_NOME_ESCRITORI_RESPONSAVEL, 1, 1024) AS DSC_NOM_ESCRITORIO_RESPONSAVEL,
  SUBSTRING(v_stt_processo.DSC_NOME_ESCRIT_ENCERRAMENTO, 1, 1024) AS DSC_NOM_ESCRIT_ENCERRAMENTO,
  SUBSTRING(v_stt_processo.DSC_NOME_FANTASIA_TERCEIRIZADA, 1, 1024) AS DSC_NOM_FANTASIA_TERCEIRIZADA,
  SUBSTRING(v_stt_processo.DSC_NOME_GESTOR, 1, 1024) AS DSC_NOM_GESTOR,
  SUBSTRING(v_stt_processo.DSC_NOME_PREPOSTO, 1, 1024) AS DSC_NOM_PREPOSTO,
  SUBSTRING(v_stt_processo.DSC_NOME_RECLAMANTE, 1, 1024) AS DSC_NOM_RECLAMANTE,
  SUBSTRING(v_stt_processo.DSC_NOME_RESPONSAVEL_ABERTURA, 1, 1024) AS DSC_NOM_RESPONSAVEL_ABERTURA,
  SUBSTRING(v_stt_processo.DSC_NOME_RESPONSA_ENCERRAMENTO, 1, 1024) AS DSC_NOM_RESPONSAVEL_ENCERRAMTO,
  SUBSTRING(v_stt_processo.COD_CENTRO_CUSTO, 1, 1024) AS DSC_NUM_CENTRO_CUSTO,
  SUBSTRING(v_stt_processo.COD_CENTRO_CUSTO_ANALISE, 1, 1024) AS DSC_NUM_CENTRO_CUSTO_ANALISE,
  SUBSTRING(v_stt_processo.COD_COMARCA, 1, 1024) AS DSC_NUM_COMARCA,
  SUBSTRING(v_stt_processo.COD_CPF_RECLAMANTE, 1, 1024) AS DSC_NUM_CPF_RECLAMANTE,
  SUBSTRING(v_stt_processo.COD_OAB_ADVOGAD_RECLAMANTE, 1, 1024) AS DSC_NUM_OAB_ADVOG_RECLAMANTE,
  SUBSTRING(v_stt_processo.COD_PROCESSO, 1, 1024) AS DSC_NUM_PROCESSO,
  SUBSTRING(v_stt_processo.COD_VARA, 1, 1024) AS DSC_NUM_VARA,
  SUBSTRING(v_stt_processo.DSC_IND_RESPOSTA_GESTOR, 1, 1024) AS DSC_RESPOSTA_GESTOR,
  SUBSTRING(v_stt_processo.DSC_IND_SITUACAO_FORNECEDOR, 1, 1024) AS DSC_SITUACAO_FORNECEDOR,
  '' AS DSC_SUBSIDIO,
  SUBSTRING(v_stt_processo.DSC_TIPO_ACAO, 1, 1024) AS DSC_TIPO_ACAO,
  SUBSTRING(v_stt_processo.DSC_IND_TIPO_PROCESSO, 1, 1024) AS DSC_TIPO_PROCESSO,
  SUBSTRING(v_stt_processo.DSC_IND_TRATAM_QUARTEIRIZACAO, 1, 1024) AS DSC_TRATAMENTO_QUARTEIRIZACAO,
  SUBSTRING(v_stt_processo.DSC_UF, 1, 1024) AS DSC_UF,
  SUBSTRING(v_stt_processo.DSC_IND_CONTR_TRABALHO_ATIVO, 1, 1024) AS IND_CONTRATO_TRABALHO_ATIVO,
  SUBSTRING(v_stt_processo.DSC_IND_CONTR_VIGENTE, 1, 1024) AS IND_CONTRATO_VIGENTE,
  SUBSTRING(v_stt_processo.DSC_IND_CRITICIDADE, 1, 1024) AS IND_CRITICIDADE,
  -- SUBSTRING(v_stt_processo.DSC_IND_EMPRESA_MONITORADA, 1, 1024) AS IND_EMPRESA_MONITORADA,
  SUBSTRING(v_stt_processo.DSC_IND_LOCALIZADO_SGT3, 1, 1024) AS IND_LOCALIZADO_SGT3,
  SUBSTRING(v_stt_processo.DSC_IND_LOCALIZADO_TERCEIRO, 1, 1024) AS IND_LOCALIZOU_TERCEIRO,
  SUBSTRING(v_stt_processo.DSC_IND_PARADIGMA, 1, 1024) AS IND_PARADIGMA,  
  SUBSTRING(v_stt_processo.DSC_IND_PERIOD_MONITORIA_ATIVO, 1, 1024) AS IND_PERIODO_MONITORIA_ATIVO,
  SUBSTRING(v_stt_processo.DSC_IND_PERIOD_TRABALHO_ATIVO, 1, 1024) AS IND_PERIODO_TRABALHO_ATIVO,
  SUBSTRING(v_stt_processo.DSC_IND_PROCESSO_PADRAO_CNJ, 1, 1024) AS IND_PROCESSO_PADRAO_CNJ,
  SUBSTRING(v_stt_processo.DSC_IND_RECLAMANTE_MONITORADO, 1, 1024) AS IND_RECLAMANTE_MONITORADO,
  SUBSTRING(v_stt_processo.DSC_IND_REJ_FORNECEDOR, 1, 1024) AS IND_REJEICAO_FORNECEDOR,
  SUBSTRING(v_stt_processo.DSC_IND_REJ_NAO_MONITORADO, 1, 1024) AS IND_REJEICAO_N_MONITORADO,
  SUBSTRING(v_stt_processo.DSC_IND_REJ_SIMPLIFICADO, 1, 1024) AS IND_REJEICAO_SIMPLIFICADO,
  -- SUBSTRING(v_stt_processo.DSC_IND_REJ_SUBSIDIO, 1, 1024) AS IND_REJEICAO_SUBSIDIO,
  SUBSTRING(v_stt_processo.DSC_IND_REJ_VALIDAR_PROCESSO, 1, 1024) AS IND_REJEICAO_VALIDAR_PROC,
  SUBSTRING(v_stt_processo.SGL_UF, 1, 1024) AS SGL_UF,
  SUBSTRING(replace(v_stt_processo.VAL_CAUSA,'.',','), 1, 1024) AS VLR_CAUSA,
  COALESCE(
(select max(DSC_NOME_EMPRESA_RECLAMADA)
   from db_mgd_corp_juridico.v_stt_empresa_reclamada reclamada
   where reclamada.COD_INSTANCIA = db_mgd_corp_juridico.v_stt_processo.cod_instancia and
         reclamada.DSC_IND_EMPRESA_PRINCIPAL = "Sim"),
(select max(DSC_NOME_EMPRESA_RECLAMADA)
   from db_mgd_corp_juridico.v_stt_empresa_reclamada reclamada
   where reclamada.COD_INSTANCIA = db_mgd_corp_juridico.v_stt_processo.cod_instancia and
         reclamada.COD_ITEM = 0)) DSC_EMPRESA_PRINCIPAL,
COALESCE(
(select max(cod_cnpj)
   from db_mgd_corp_juridico.v_stt_empresa_reclamada reclamada
   where reclamada.COD_INSTANCIA = db_mgd_corp_juridico.v_stt_processo.cod_instancia and
         reclamada.DSC_IND_EMPRESA_PRINCIPAL = "Sim"),
(select max(cod_cnpj)
   from db_mgd_corp_juridico.v_stt_empresa_reclamada reclamada
   where reclamada.COD_INSTANCIA = db_mgd_corp_juridico.v_stt_processo.cod_instancia and
         reclamada.COD_ITEM = 0)) DSC_CNPJ_EMPRESA_PRINCIPAL,
coalesce(
(select max(DSC_IND_EMPRESA_PRINCIPAL)
   from db_mgd_corp_juridico.v_stt_empresa_reclamada reclamada
   where reclamada.COD_INSTANCIA = db_mgd_corp_juridico.v_stt_processo.cod_instancia and
         DSC_IND_EMPRESA_PRINCIPAL = "Sim"), 
"") DSC_IND_EMPRESA_PRINCIPAL,
(SELECT group_concat(CASE WHEN DSC_USUARIO_GRUPO LIKE 'ESCRITORIO%' THEN     'ESCRITORIO ADVOCACIA' ELSE DSC_USUARIO_GRUPO END separator ' / ')  AS DSC_AREA_ATIVA
FROM db_mgd_corp_juridico.v_stt_tarefa
WHERE DSC_STATUS!='Closed' AND
      COD_INSTANCIA =  db_mgd_corp_juridico.v_stt_processo.COD_INSTANCIA
GROUP BY COD_INSTANCIA) DSC_AREA_ATIVA,

COALESCE(
(select max(DSC_IND_MONITORADO)
   from db_mgd_corp_juridico.v_stt_empresa_reclamada reclamada
   where reclamada.COD_INSTANCIA = db_mgd_corp_juridico.v_stt_processo.cod_instancia and
         reclamada.DSC_IND_EMPRESA_PRINCIPAL = "Sim"),
(select max(DSC_IND_MONITORADO)
   from db_mgd_corp_juridico.v_stt_empresa_reclamada reclamada
   where reclamada.COD_INSTANCIA = db_mgd_corp_juridico.v_stt_processo.cod_instancia and
         reclamada.COD_ITEM = 0)) "IND_EMPRESA_MONITORADA"

FROM db_mgd_corp_juridico.v_stt_processo
